Failure test case for manual install
Testing for scenario where longer job fails

diff --git a/.github/workflows/test-with-manual-install.yml b/.github/workflows/test-with-manual-install.yml
--- a/.github/workflows/test-with-manual-install.yml
+++ b/.github/workflows/test-with-manual-install.yml
@@ -31,8 +31,8 @@ jobs:
    
       - name: Success-Failure Test Case
         run: |
-          echo "Test successful" && exit 0
-          # echo "Test failed" && exit 1
+          # echo "Test successful" && exit 0
+          echo "Test failed" && exit 1
 
 # # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 # jobs:
