Commented sample success failure tests

diff --git a/.github/workflows/test-with-docker.yml b/.github/workflows/test-with-docker.yml
--- a/.github/workflows/test-with-docker.yml
+++ b/.github/workflows/test-with-docker.yml
@@ -13,37 +13,37 @@ on:
 
   workflow_call:
 
-jobs: 
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Run test-with-docker for 30 seconds
-        run: |
-          echo "Starting 30-second workflow"
-          sleep 30
-          echo "30-second workflow completed"
-
-      - name: Success-Failure Test Case
-        run: |
-          # echo "Test successful" && exit 0
-          echo "Test failed" && exit 1
-
-
-# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
-# jobs:
-#   # This workflow contains a single job called "build"
+# jobs: 
 #   build:
-#     # The type of runner that the job will run on
 #     runs-on: ubuntu-latest
-
-#     # Steps represent a sequence of tasks that will be executed as part of the job
 #     steps:
-#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-#     - name: Checkout
-#       uses: actions/checkout@v2
+#       - name: Run test-with-docker for 30 seconds
+#         run: |
+#           echo "Starting 30-second workflow"
+#           sleep 30
+#           echo "30-second workflow completed"
 
-#     - name: Make sure that the workflow works
-#       run: echo Smoke test
+#       - name: Success-Failure Test Case
+#         run: |
+#           echo "Test successful" && exit 0
+#           # echo "Test failed" && exit 1
 
-#     - name: Run the tests using docker-compose
-#       run: docker compose -f setup/docker-compose.tests.yml up --exit-code-from web-server
+
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+jobs:
+  # This workflow contains a single job called "build"
+  build:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+    - name: Checkout
+      uses: actions/checkout@v2
+
+    - name: Make sure that the workflow works
+      run: echo Smoke test
+
+    - name: Run the tests using docker-compose
+      run: docker compose -f setup/docker-compose.tests.yml up --exit-code-from web-server
diff --git a/.github/workflows/test-with-manual-install.yml b/.github/workflows/test-with-manual-install.yml
--- a/.github/workflows/test-with-manual-install.yml
+++ b/.github/workflows/test-with-manual-install.yml
@@ -15,72 +15,72 @@ on:
 
   workflow_call:
 
-jobs: 
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Run test-with-manual-install for 1 minute
-        run: |
-          echo "Starting 1-minute workflow"
-          sleep 60
-          echo "1-minute workflow completed"
-   
-      - name: Success-Failure Test Case
-        run: |
-          echo "Test successful" && exit 0
-          # echo "Test failed" && exit 1
-
-# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
-# jobs:
-#   # This workflow contains a single job called "build"
+# jobs: 
 #   build:
-#     # The type of runner that the job will run on
-#     runs-on: ${{ matrix.os }}
-#     strategy:
-#       matrix:
-#         os: [ubuntu-latest]
-
-#     # Steps represent a sequence of tasks that will be executed as part of the job
+#     runs-on: ubuntu-latest
 #     steps:
-#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-#     - uses: actions/checkout@v2
+#       - name: Run test-with-manual-install for 1 minute
+#         run: |
+#           echo "Starting 1-minute workflow"
+#           sleep 60
+#           echo "1-minute workflow completed"
+   
+#       - name: Success-Failure Test Case
+#         run: |
+#           echo "Test successful" && exit 0
+#           # echo "Test failed" && exit 1
 
-#     - name: Install and start MongoDB
-#       uses: supercharge/mongodb-github-action@1.3.0
-#       with:
-#         mongodb-version: 4.4.0
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+jobs:
+  # This workflow contains a single job called "build"
+  build:
+    # The type of runner that the job will run on
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
 
-#     - name: Check existing version of miniconda
-#       shell: bash -l {0}
-#       run: conda info -a
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+    - uses: actions/checkout@v2
 
-#     - name: Install miniconda
-#       shell: bash -l {0}
-#       run: |
-#         source setup/setup_conda.sh Linux-x86_64
+    - name: Install and start MongoDB
+      uses: supercharge/mongodb-github-action@1.3.0
+      with:
+        mongodb-version: 4.4.0
 
-#     - name: Check whether the CI environment variable is set
-#       shell: bash -l {0}
-#       run: |
-#         source setup/activate_conda.sh
-#         echo $CI
+    - name: Check existing version of miniconda
+      shell: bash -l {0}
+      run: conda info -a
 
-#     - name: Setup the emission environment for testing
-#       shell: bash -l {0}
-#       run: |
-#         conda --version
-#         which conda
-#         source setup/activate_conda.sh
-#         conda --version
-#         source setup/setup_tests.sh
+    - name: Install miniconda
+      shell: bash -l {0}
+      run: |
+        source setup/setup_conda.sh Linux-x86_64
 
-#     - name: Switch to emission and run the tests
-#       shell: bash -l {0}
-#       run: |
-#         source setup/activate_tests.sh
-#         conda --version
-#         ./runAllTests.sh
+    - name: Check whether the CI environment variable is set
+      shell: bash -l {0}
+      run: |
+        source setup/activate_conda.sh
+        echo $CI
 
-#     - name: Teardown the test environment
-#       shell: bash -l {0}
-#       run: source setup/teardown_tests.sh
+    - name: Setup the emission environment for testing
+      shell: bash -l {0}
+      run: |
+        conda --version
+        which conda
+        source setup/activate_conda.sh
+        conda --version
+        source setup/setup_tests.sh
+
+    - name: Switch to emission and run the tests
+      shell: bash -l {0}
+      run: |
+        source setup/activate_tests.sh
+        conda --version
+        ./runAllTests.sh
+
+    - name: Teardown the test environment
+      shell: bash -l {0}
+      run: source setup/teardown_tests.sh
